travis:
  secure:
    BINSTAR_TOKEN: FtL6pFQzQXNbKrX/PjgM1VJwdCCNz0jpJCVasSRytmDB843Z4d2dgXv/7xsrgKRF7oj7lGPRSgDyAcxSaBv08+YA4uKcrrvddzNcfcJoTXye56FG4ST0hA0cMO0AEZ00dbRaiB+X/1KDopXSRq5Ev4Z2pm4vzzSdQ/UmK7LFRpaNb8L49WBtrrBRV/YCTdUTCHMA1hKEStbnn6umfGEnGSkgihuYQsmlM29b+Z0LbraI936LucqyZ74c5B+WUA83TgnTDhuYHJfSWC4VLzFlD9h5fFOPAiF/Ueh3fpZeLPWxqMv5eLlsGVMjXeeBa1w/PLNGKhBOU9JubbM5Wncm3XupKV9BxmCCWHqrhkE32f7geUzNw1Ef8H21Nlu6p1RJXCJepnfEuxQINdaj2w77b+2ngLDwluuhWivZT9tmXvzq4NXSm9cSataPz6UB63t+97AOL4EV/QN2CDiDLUEyJheI91v06ZarWnO3lfqmdc7vHzEPdjoRUualX/kkXkuShwE1Y3anMaglXyE8x8sjsIImUnyCjQb5Me6000Aa43IrLoJsdmKADowQB22ZAMUNVj7Z+PuktFRzHqQDE5VaFqlo8YLoT7UdR6v9l5PrgHXGu0aeSl1I6stLyoO5MMD18fkHOSKrFwWalYEU+hNdiIpsaIT7lndGwn7L+2hR9gg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
